### PR TITLE
 Introduce Deployment Pipeline and Enforce Dev-to-Prod Merges

### PR DESCRIPTION
**Pull request by cheesea3**
**Summary**  
This PR adds two GitHub Actions workflows that streamline our deployment process and protect the `prod` branch from accidental or direct merges that bypass `dev`.

1. **`deployment_pipeline.yml`**  
   - **Trigger**: Runs on any push to `dev` or `prod`.  
   - **Behavior**:  
     - If the push lands on `dev`, deploys the `./sites` directory to `/stocker/sites/dev`.  
     - If the push lands on `prod`, deploys `./sites` to `/stocker/sites/prod`.  
   - **Outcome**: Allows continuous deployment for both dev and production environments.

2. **`prod_pr_guard.yml`**  
   - **Trigger**: Runs on any pull request targeting `prod`.  
   - **Behavior**: Checks the source (head) branch of the PR. If it isn’t `dev`, the workflow fails with an error.  
   - **Outcome**: Ensures that merges into `prod` only come from `dev`, preventing hotfix or feature branches from accidentally skipping the dev environment.

**Why These Changes?**  
- We want a clear two-stage environment workflow: code is first merged into `dev` for testing, then merged from `dev` into `prod` when ready.  
- The new `deployment_pipeline.yml` workflow automates the file transfer to the correct environment upon each merge.  
- `prod_pr_guard.yml` provides an extra safety net to enforce our branch model strictly, ensuring `prod` remains stable and only receives changes already tested in `dev`.

**How to Test**  
1. **Deploy to Dev**  
   - Merge any branch into `dev`. The push event triggers a deployment to `/stocker/sites/dev`.  
2. **Promote to Prod**  
   - Merge `dev` into `prod`. The push event triggers a deployment to `/stocker/sites/prod`.  
3. **Try Merging Non-Dev Branch into Prod**  
   - Open a PR targeting `prod` from something other than `dev`. The `prod_pr_guard.yml` check should fail, blocking the merge.

**Next Steps**  
- Make sure to enable branch protection rules for `dev` and `prod` so direct pushes are disallowed and PRs are required.  
- Mark the “Enforce merges from dev only” check as **required** in `prod`’s branch protection settings.

Please review the workflows for accuracy and let me know if any changes or refinements are needed. Once approved and merged, these files will ensure a consistent, safe, and automated deployment flow for our project.

### CODE REVIEW

**Comment by cheesea3** [comment]
site_topology

**Comment by Channave** [comment]
LGTM 👍 PR approved and merged.

**Comment by cheesea3** [comment]
wait open it - I'm locked up
They won't let me out (No!)

**Comment by cheesea3** [comment]
For future reference.

### Flow
1. Create an ‘issue’.
2. Go to Dev branch.
3. Create a new branch based off dev branch OR create issue of issue.
4. Make the changes required.
5. Create pull request.
6. Accept pull request.
7. Merged to dev then deployed to dev environment through GitHub actions workflow.
8. Create pull request from dev branch to merge into prod branch.
9. Accept pull request to trigger workflow to deploy to prod environment.

**Pull request merged**
